server:
  port: 20000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:  http://localhost:20000/eureka/
    register-with-eureka: false
    fetch-registry: false